**代码演示部分：配合本章学习材料使用**  
**第一部分：张量运算示例**  
这里将演示Tensor的一些基本操作

In [43]:
import torch

In [44]:
?torch.tensor

Docstring:
tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor

Constructs a tensor with :attr:`data`.

.. warning::

    :func:`torch.tensor` always copies :attr:`data`. If you have a Tensor
    ``data`` and want to avoid a copy, use :func:`torch.Tensor.requires_grad_`
    or :func:`torch.Tensor.detach`.
    If you have a NumPy ``ndarray`` and want to avoid a copy, use
    :func:`torch.as_tensor`.

.. warning::

    When data is a tensor `x`, :func:`torch.tensor` reads out 'the data' from whatever it is passed,
    and constructs a leaf variable. Therefore ``torch.tensor(x)`` is equivalent to ``x.clone().detach()``
    and ``torch.tensor(x, requires_grad=True)`` is equivalent to ``x.clone().detach().requires_grad_(True)``.
    The equivalents using ``clone()`` and ``detach()`` are recommended.

Args:
    data (array_like): Initial data for the tensor. Can be a list, tuple,
        NumPy ``ndarray``, scalar, and other types.

Keyword args:
    dtyp

In [45]:
# 创建tensor，用dtype指定类型。注意类型要匹配
a = torch.tensor(1.0, dtype=torch.float)
b = torch.tensor(1, dtype=torch.long)
c = torch.tensor(1.0, dtype=torch.int8)
print(a, b, c)

tensor(1.) tensor(1) tensor(1, dtype=torch.int8)


/tmp/ipykernel_19868/512902504.py:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  c = torch.tensor(1.0, dtype=torch.int8)


In [46]:
# 使用指定类型函数随机初始化指定大小的tensor
d = torch.FloatTensor(2,3)
e = torch.IntTensor(2)
f = torch.IntTensor([1,2,3,4])  #对于python已经定义好的数据结构可以直接转换
print(d, '\n', e, '\n', f)

tensor([[-2.9783e-10,  4.5900e-41, -2.9783e-10],
        [ 4.5900e-41,  4.4842e-44,  0.0000e+00]]) 
 tensor([-866198768,      22003], dtype=torch.int32) 
 tensor([1, 2, 3, 4], dtype=torch.int32)


In [47]:
# tensor和numpy array之间的相互转换
import numpy as np

g = np.array([[1,2,3],[4,5,6]])
h = torch.tensor(g)
print(h)
i = torch.from_numpy(g)
print(i)
j = h.numpy()
print(j)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


注意：torch.tensor创建得到的张量和原数据是不共享内存的，张量对应的变量是独立变量。  
而torch.from_numpy()和torch.as_tensor()从numpy array创建得到的张量和原数据是共享内存的，张量对应的变量不是独立变量，修改numpy array会导致对应tensor的改变。

In [48]:
g[0,0] = 100
print(i)

tensor([[100,   2,   3],
        [  4,   5,   6]])


In [49]:
# 常见的构造Tensor的函数
k = torch.rand(2, 3) 
l = torch.ones(2, 3)
m = torch.zeros(2, 3)
n = torch.arange(0, 10, 2)
print(k, '\n', l, '\n', m, '\n', n)

tensor([[0.6887, 0.5680, 0.9846],
        [0.2661, 0.2388, 0.7622]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([0, 2, 4, 6, 8])


In [50]:
# 查看tensor的维度信息（两种方式）
print(k.shape)
print(k.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [51]:
# tensor的运算
o = torch.add(k,l)
print(o)

tensor([[1.6887, 1.5680, 1.9846],
        [1.2661, 1.2388, 1.7622]])


In [52]:
# tensor的索引方式与numpy类似
print(o[:,1])
print(o[0,:])

tensor([1.5680, 1.2388])
tensor([1.6887, 1.5680, 1.9846])


In [53]:
# 改变tensor形状的神器：view
print(o.view((3,2)))
print(o.view(-1,2))

tensor([[1.6887, 1.5680],
        [1.9846, 1.2661],
        [1.2388, 1.7622]])
tensor([[1.6887, 1.5680],
        [1.9846, 1.2661],
        [1.2388, 1.7622]])


In [54]:
# tensor的广播机制（使用时要注意这个特性）
p = torch.arange(1, 3).view(1, 2)
print(p)
q = torch.arange(1, 4).view(3, 1)
print(q)
print(p + q)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [55]:
# 扩展&压缩tensor的维度：squeeze
print(o)
print(o.shape)
r = o.unsqueeze(1)
print(r)
print(r.shape)

tensor([[1.6887, 1.5680, 1.9846],
        [1.2661, 1.2388, 1.7622]])
torch.Size([2, 3])
tensor([[[1.6887, 1.5680, 1.9846]],

        [[1.2661, 1.2388, 1.7622]]])
torch.Size([2, 1, 3])


In [56]:
s = r.squeeze(0)
print(s)
print(r.shape, s.shape)

tensor([[[1.6887, 1.5680, 1.9846]],

        [[1.2661, 1.2388, 1.7622]]])
torch.Size([2, 1, 3]) torch.Size([2, 1, 3])


In [57]:
t = r.squeeze(1)
print(t)
print(r.shape, t.shape)

tensor([[1.6887, 1.5680, 1.9846],
        [1.2661, 1.2388, 1.7622]])
torch.Size([2, 1, 3]) torch.Size([2, 3])


**第二部分：自动求导示例**  
这里将通过一个简单的函数  $y=x_1+2*x_2$  来说明PyTorch自动求导的过程

In [58]:
import torch

x1 = torch.tensor(2.0, requires_grad=True)
x2 = torch.tensor(2.0, requires_grad=True)
y = x1 + 2*x2
print(y)

tensor(6., grad_fn=<AddBackward0>)


In [59]:
# 首先查看每个变量是否需要求导
print(x1.requires_grad)
print(x2.requires_grad)
print(y.requires_grad)

True
True
True


In [60]:
# 查看每个变量导数大小。此时因为还没有反向传播，因此导数都不存在
print(x1.grad.data)
print(x2.grad.data)
print(y.grad.data)

AttributeError: 'NoneType' object has no attribute 'data'

In [62]:
x1

tensor(2., requires_grad=True)

In [63]:
## 反向传播后看导数大小
y = x1 + 2*x2
y.backward()
print(x1.grad.data)
print(x2.grad.data)

tensor(1.)
tensor(2.)


In [64]:
# 导数是会累积的，重复运行相同命令，grad会增加
y = x1 ** 2 + 2*x2
y.backward()
print(x1.grad.data)
print(x2.grad.data)
x1.grad.zero_()
x2.grad.zero_()

tensor(5.)
tensor(4.)


tensor(0.)

In [65]:
# 所以每次计算前需要清除当前导数值避免累积，这一功能可以通过pytorch的optimizer实现。后续会讲到

In [66]:
# 尝试，如果不允许求导，会出现什么情况？
x1 = torch.tensor(1.0, requires_grad=False)
x2 = torch.tensor(2.0, requires_grad=False)
y = x1 + 2*x2
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn